// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testWPF.Data;

#nullable disable

namespace testWPF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727103117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("testWPF.Models.TuberculosisCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresseComplete")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuDelaFrottis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDebutTraitement")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEnregistrement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decede")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Echec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fin2eMoisCult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fin2eMoisFrottis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fin4eMoisCult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fin4eMoisFrottis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuerisTraitTermine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LieuDebutTraitement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("LungDrawing")
                        .HasColumnType("BLOB");

                    b.Property<string>("Mois6ou8Cult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mois6ou8Frottis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomPrenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumeroOrdre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasExamenBacteriol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PerduDeVue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreTraitCult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreTraitFrottis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegimeTraitement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TpOuTep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transfere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TypeA")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TypeE")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TypeN")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TypeR")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TypeREP")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TypeT")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
